version: "3.7"

services:
  api:
    build: .
    container_name: artistweb-api
    ports:
      - "8080:8080"
    networks:
      - bobby_network

  postgres:
    image: postgres:latest
    container_name: artistweb-api-postgres
    environment:
      POSTGRES_USER: golna
      POSTGRES_PASSWORD: golna
      POSTGRES_DB: artistweb
    ports:
      - "5432:5432"
    networks:
      - bobby_network
    volumes:
      - postgres-artistWeb-data:/var/lib/postgresql/data

networks:
  bobby_network:
    driver: bridge

volumes:
  postgres-artistWeb-data: